name: 🎉 Release Binary

on:
  push:
    tags:
      - "v*" # 仅匹配版本标签，如 v1.0.0
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 明确指定写入权限
    env:
      GOPRIVATE: github.com/zan8in
      GOPROXY: https://proxy.golang.org,direct
      GONOSUMDB: github.com/zan8in

    steps:
      - uses: actions/checkout@v4 # 更新到v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.24" # 使用稳定版本

      - name: Download and verify Go modules
        run: |
          go mod download
          go mod verify

      - uses: goreleaser/goreleaser-action@v5 # 更新到v5
        with:
          args: release --clean
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用默认token
          GOPRIVATE: github.com/zan8in
          GOPROXY: https://proxy.golang.org,direct
          GONOSUMDB: github.com/zan8in
