name: 🎉 Release Binary

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GOPRIVATE: github.com/zan8in
      GOPROXY: https://proxy.golang.org,direct
      GONOSUMDB: github.com/zan8in

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.x # 使用最新 Go 版本

      - name: Download and verify Go modules
        run: |
          go mod download
          go mod verify

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean # 添加 --clean
          version: "~> v2" # 修改版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPRIVATE: github.com/zan8in
          GOPROXY: https://proxy.golang.org,direct
          GONOSUMDB: github.com/zan8in
